name: Docker Image Small Alpine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./latest
          file: ./latest/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rstudio-verse
      -
        name: Build and Push v4.2.0
        id: docker_build_four_two_zero
        uses: docker/build-push-action@v2
        with:
          context: 4.2.0
          file: latest/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rstudio-verse:4.2.0   
