name: Docker Hub Push

on:
  push:
    branches: [ main ]
    
jobs:

  build:
    runs-on: ubuntu-20.04
    
    steps:
    
      - name: checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push 
        id: docker_build
        uses: docker/build-push-action@v2.6.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: latest
          dockerfile: Dockerfile
          repository: cyversevice/rstudio
          tags: latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
